### ISSUE TITLE
运行中突然报错FastDFSException:get storage failed

### ISSUE THREAD

**Issue by ZZeroFly** [happyfish100/fastdfs-client-java#10]
运行中突然报异常FastDFSException:get storage failed
查看storage和tracker服务器日志均没有报错
重启client所在的tomcat后正常
但是运行一段时间后，错误再次出现
这个是什么原因啊，无从下手

**Comment by 0312birdzhang** [comment]
tracker跟storage通信有问题吧

**Comment by ZZeroFly** [comment]
后来发现是磁盘空间不足引起的，tracker无法找到一台可用的（剩余足够空间的）storage。
