### ISSUE TITLE
请问一下fastdfs client能否指定上传的目录呢？

### ISSUE THREAD

**Issue by jack-131** [happyfish100/fastdfs-client-java#105]
类似于 /g2/M00/00/02/wKgyJ2QZVXiAHw5yAAOvzl9X2rw70.jpeg，指定为/g2/M00/11/11/wKgyJ2QZVXiAHw5yAAOvzl9X2rw70.jpeg，指定中间的/11/11 @happyfish100

**Comment by jack-131** [comment]
跪求大佬解答

**Comment by happyfish100** [comment]
不支持
