### ISSUE TITLE
压力测试报空指针异常。

### ISSUE THREAD

**Issue by ityouknow** [happyfish100/fastdfs-client-java#27]
在进行压力测试的时候，发现只要有并发就会报空指针异常。

`java.lang.NullPointerException    
	at org.csource.fastdfs.StorageClient.do_upload_file(StorageClient.java:862)  
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:208)  
	at org.csource.fastdfs.StorageClient.upload_file(StorageClient.java:226)`

跟踪了一下代码，发现`this.storageServer` 是一个全局变量，在多线程访问的情况下会产生并发。

我看代码的逻辑是，在进入方法的时候给`this.storageServer` 赋值，在方法退出的时候释放掉，但是如果在一个线程在释放的时候一个线程刚好进去方法就会产生空指针异常。

解决办法有两种:
1) 给方法加上synchronized 避免并发。
2)使用threadlocal来存储storageServer

我本机测试的时候加上synchronized 进行压测就不再出现问题了。不知道大家是否也会遇到这个问题。

**Comment by ityouknow** [comment]
参考这个：https://github.com/happyfish100/fastdfs-client-java/pull/28

**Comment by treeke** [comment]
遇到一样的问题，最开始也是用了一个ArrayList +Synchronized 维护创建的StorageClient，后来改成ConcurrentLinkedQueue<StorageClient>  一个基于cas操作的非阻塞队列，这个比较好用
