### ISSUE TITLE
【分享问题】upload方法如果通过available()获取文件大小值大于INT的最大值，将会发生越界异常

### ISSUE THREAD

**Issue by ebrx** [happyfish100/fastdfs-client-java#95]
您好，在测试片段中，upload方法如果通过available()获取文件大小值大于INT的最大值时，创建byte[]发生越界异常。

## 发生场景
生产实际运行过程中，接收到外部系统发送文件大于3GB，通过fastdfs-client-java上传api上传发生异常，因为之前没有遇到过这么大的文件，系统运行两年，发生该异常。

## 测试代码
```java
 @Test
    public void upload() throws Exception{
        NameValuePair[] metaList = new NameValuePair[1];
        String local_filename = "RHEL-server-7.0-x86_64-LinuxProbe.Com.iso";
        metaList[0] = new NameValuePair("fileName", local_filename);
        File file = new File("/Volumes/ExtremeSSD/vm/RHEL-server-7.0-x86_64-LinuxProbe.Com.iso");
        InputStream inputStream = new FileInputStream(file);
        int length = inputStream.available();
        byte[] bytes = new byte[length];// 发生异常位置
        inputStream.read(bytes);
        String[] result = storageClient.upload_file(bytes, null, metaList);
        LOGGER.info("result {}", Arrays.asList(result));
        Assert.assertEquals(2, result.length);
    }
```
## 异常信息
  如果文件大小超过超过 Integer.MAX_VALUE 2147483647
  new byte[Integer.MAX_VALUE+1]
  抛出异常
  java.lang.OutOfMemoryError: Requested array size exceeds VM limit

## Requested array size exceeds VM limit 概述(网络描述)
Java对你的应用可以分配的最大数组大小有限制. 准确的限制与平台有关, 但是通常都位于10到21亿元素之间.

**Comment by marshalcn** [comment]
没见过操作io的时候一口气把字节流全读出来的，而且看样子你这文件也不小，你这问题建议你再好好学学java io这块

**Comment by ebrx** [comment]
这是demo里面的测试代码，并非个人所写。
